name: Terraform

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    uses: silinternational/workflows/.github/workflows/terraform.yml@main
    with:
      # validate with the earliest version allowed by required_version in versions.tf
      terraform-version: '~> 0.12'
      test-dir: 'test'
